const data = {
    "results": [
        {
            "id": 10,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/10/?format=api",
            "name": "Apollo Command/Service Module",
            "agency": {
                "id": 999,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/999/?format=api",
                "name": "North American Aviation",
                "featured": false,
                "type": "Commercial",
                "country_code": "USA",
                "abbrev": "BOI",
                "description": "North American Aviation (NAA) was a major American aerospace manufacturer, responsible for a number of historic aircraft, including the T-6 Texan trainer, the P-51 Mustang fighter, the B-25 Mitchell bomber, the F-86 Sabre jet fighter, the X-15 rocket plane, and the XB-70, as well as Apollo command and service module, the second stage of the Saturn V rocket, the Space Shuttle orbiter and the B-1 Lancer.",
                "administrator": 'Hel Lahot',
                "founding_year": "1928",
                "launchers": "North American X-15",
                "spacecraft": "",
                "parent": "Boeing",
                "image_url": 'https://pages.museumofflight.org/hs-fs/hubfs/Development%20Campaigns/Moon%20Day%202018/NMD_ApolloCM.jpg?width=1260&name=NMD_ApolloCM.jpg',
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/north2520american2520aviation_logo_20200711032022.png"
            },
            "in_use": false,
            "capability": "Cargo and Human Transportation to Lunar Orbit",
            "maiden_flight": "1966-02-26",
            "human_rated": true,
            "crew_capacity": 3,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/apollo2520command2fservice2520module_image_20190207032507.jpeg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Apollo_Command/Service_Module",
            "info_link": ""
        },
        {
            "id": 43,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/43/?format=api",
            "name": "Apollo Lunar Module",
            "agency": {
                "id": 44,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/44/?format=api",
                "name": "National Aeronautics and Space Administration",
                "featured": true,
                "type": "Government",
                "country_code": "USA",
                "abbrev": "NASA",
                "description": "The National Aeronautics and Space Administration is an independent agency of the executive branch of the United States federal government responsible for the civilian space program, as well as aeronautics and aerospace research. NASA have many launch facilities but most are inactive. The most commonly used pad will be LC-39B at Kennedy Space Center in Florida.",
                "administrator": "Administrator: Bill Nelson",
                "founding_year": "1958",
                "launchers": "Space Shuttle | SLS",
                "spacecraft": "Orion",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/national2520aeronautics2520and2520space2520administration_image_20190207032448.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/national2520aeronautics2520and2520space2520administration_logo_20190207032448.png"
            },
            "in_use": false,
            "capability": "Landing on the Moon, Rendezvous in lunar orbit",
            "maiden_flight": "1968-01-22",
            "human_rated": true,
            "crew_capacity": 2,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/lunar_module_on_image_20240505074251.jpeg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Apollo_Lunar_Module",
            "info_link": ""
        },
        {
            "id": 17,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/17/?format=api",
            "name": "Automated Transfer Vehicle (ATV)",
            "agency": {
                "id": 115,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/115/?format=api",
                "name": "Arianespace",
                "featured": true,
                "type": "Commercial",
                "country_code": "FRA",
                "abbrev": "ASA",
                "description": "Arianespace SA is a multinational company founded in 1980 as the world's first commercial launch service provider. It undertakes the production, operation, and marketing of the Ariane programme. Their vehicles launch exclusively from French Guiana in South America.",
                "administrator": "CEO: Stéphane Israël",
                "founding_year": "1980",
                "launchers": "Ariane | Vega",
                "spacecraft": "",
                "parent": "ArianeGroup",
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/arianespace_image_20190207032425.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/arianespace_logo_20210603173752.png"
            },
            "in_use": false,
            "capability": "Cargo Earth Orbit Logistics",
            "maiden_flight": "2008-03-09",
            "human_rated": false,
            "crew_capacity": null,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/automated_trans_image_20231118111716.jpeg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Automated_Transfer_Vehicle",
            "info_link": ""
        },
        {
            "id": 28,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/28/?format=api",
            "name": "Buran",
            "agency": {
                "id": 63,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/63/?format=api",
                "name": "Russian Federal Space Agency (ROSCOSMOS)",
                "featured": true,
                "type": "Government",
                "country_code": "RUS",
                "abbrev": "RFSA",
                "description": "The Roscosmos State Corporation for Space Activities, commonly known as Roscosmos, is the governmental body responsible for the space science program of the Russian Federation and general aerospace research. Soyuz has many launch locations the Russian sites are Baikonur, Plesetsk and Vostochny however Ariane also purchases the vehicle and launches it from French Guiana.",
                "administrator": "Administrator: Yuri Borisov",
                "founding_year": "1992",
                "launchers": "Soyuz",
                "spacecraft": "Soyuz",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/russian2520federal2520space2520agency25202528roscosmos2529_image_20190207032459.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/russian2520federal2520space2520agency25202528roscosmos2529_logo_20190207032459.png"
            },
            "in_use": false,
            "capability": "Autonomously carrying cargo and crew (never achieved) to Low Earth Orbit.",
            "maiden_flight": "1988-11-15",
            "human_rated": true,
            "crew_capacity": 4,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/buran_image_20210902151254.jpg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Buran_(spacecraft)",
            "info_link": ""
        },
        {
            "id": 7,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/7/?format=api",
            "name": "Cargo Dragon 2",
            "agency": {
                "id": 121,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/121/?format=api",
                "name": "SpaceX",
                "featured": true,
                "type": "Commercial",
                "country_code": "USA",
                "abbrev": "SpX",
                "description": "Space Exploration Technologies Corp., known as SpaceX, is an American aerospace manufacturer and space transport services company headquartered in Hawthorne, California. It was founded in 2002 by entrepreneur Elon Musk with the goal of reducing space transportation costs and enabling the colonization of Mars. SpaceX operates from many pads, on the East Coast of the US they operate from SLC-40 at Cape Canaveral Space Force Station and historic LC-39A at Kennedy Space Center. They also operate from SLC-4E at Vandenberg Space Force Base, California, usually for polar launches. Another launch site is being developed at Boca Chica, Texas.",
                "administrator": "CEO: Elon Musk",
                "founding_year": "2002",
                "launchers": "Falcon | Starship",
                "spacecraft": "Dragon",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/spacex_image_20190207032501.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/spacex_logo_20220826094919.png"
            },
            "in_use": true,
            "capability": "Cargo Earth Orbit Logistics",
            "maiden_flight": "2020-12-06",
            "human_rated": false,
            "crew_capacity": null,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/crs-28_dragon_d_image_20230530191602.jpeg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Dragon_2",
            "info_link": "https://www.spacex.com/dragon"
        },
        {
            "id": 31,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/31/?format=api",
            "name": "Chinese reusable spacecraft",
            "agency": {
                "id": 88,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/88/?format=api",
                "name": "China Aerospace Science and Technology Corporation",
                "featured": true,
                "type": "Government",
                "country_code": "CHN",
                "abbrev": "CASC",
                "description": "The China Aerospace Science and Technology Corporation (CASC) is the main contractor for the Chinese space program. It is state-owned and has a number of subordinate entities which design, develop and manufacture a range of spacecraft, launch vehicles, strategic and tactical missile systems, and ground equipment. It was officially established in July 1999 as part of a Chinese government reform drive, having previously been one part of the former China Aerospace Corporation. Various incarnations of the program date back to 1956.",
                "administrator": "Chairman & President: Lei Fanpei",
                "founding_year": "1999",
                "launchers": "Long March",
                "spacecraft": "",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/china2520aerospace2520science2520and2520technology2520corporation_image_20191228094408.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/china2520aerospace2520science2520and2520technology2520corporation_logo_20220826093937.png"
            },
            "in_use": true,
            "capability": "Reusable technology demonstration test bed for orbital and re-entry operations.",
            "maiden_flight": "2020-09-04",
            "human_rated": false,
            "crew_capacity": null,
            "image_url": 'https://static.scientificamerican.com/sciam/cache/file/55D2D6F5-230B-4D68-B0070015E69F23DF_source.jpg',
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Chinese_reusable_experimental_spacecraft",
            "info_link": ""
        },
        {
            "id": 22,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/22/?format=api",
            "name": "Crew Capsule 1",
            "agency": {
                "id": 141,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/141/?format=api",
                "name": "Blue Origin",
                "featured": true,
                "type": "Commercial",
                "country_code": "USA",
                "abbrev": "BO",
                "description": "Blue Origin is an American privately funded aerospace manufacturer and spaceflight services company set up by Amazon.com founder Jeff Bezos with its headquarters in Kent, Washington. The company is developing technologies to enable private human access to space with the goal to dramatically lower costs and increase reliability. Blue Origin currently launches its New Shepard sub-orbital vehicle from its West Texas launch site, they are currently constructing a launch pad for their orbital vehicle New Glenn at Cape Canaveral LC-36.",
                "administrator": "CEO: Jeff Bezos",
                "founding_year": "2000",
                "launchers": "New Shepard | New Glenn",
                "spacecraft": "",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/blue2520origin_image_20190207032427.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/blue2520origin_logo_20190207032427.png"
            },
            "in_use": false,
            "capability": "It carries cargo.",
            "maiden_flight": "2015-04-29",
            "human_rated": false,
            "crew_capacity": null,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/crew2520capsule25201_image_20190309100308.jpg",
            "nation_url": null,
            "wiki_link": "",
            "info_link": ""
        },
        {
            "id": 21,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/21/?format=api",
            "name": "Crew Capsule 2.0",
            "agency": {
                "id": 141,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/141/?format=api",
                "name": "Blue Origin",
                "featured": true,
                "type": "Commercial",
                "country_code": "USA",
                "abbrev": "BO",
                "description": "Blue Origin is an American privately funded aerospace manufacturer and spaceflight services company set up by Amazon.com founder Jeff Bezos with its headquarters in Kent, Washington. The company is developing technologies to enable private human access to space with the goal to dramatically lower costs and increase reliability. Blue Origin currently launches its New Shepard sub-orbital vehicle from its West Texas launch site, they are currently constructing a launch pad for their orbital vehicle New Glenn at Cape Canaveral LC-36.",
                "administrator": "CEO: Jeff Bezos",
                "founding_year": "2000",
                "launchers": "New Shepard | New Glenn",
                "spacecraft": "",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/blue2520origin_image_20190207032427.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/blue2520origin_logo_20190207032427.png"
            },
            "in_use": true,
            "capability": "Crew and Cargo Flights",
            "maiden_flight": "2017-12-12",
            "human_rated": true,
            "crew_capacity": 6,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/crew2520capsule25202.0_image_20190309095011.jpeg",
            "nation_url": null,
            "wiki_link": "",
            "info_link": ""
        },
        {
            "id": 6,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/6/?format=api",
            "name": "Crew Dragon 2",
            "agency": {
                "id": 121,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/121/?format=api",
                "name": "SpaceX",
                "featured": true,
                "type": "Commercial",
                "country_code": "USA",
                "abbrev": "SpX",
                "description": "Space Exploration Technologies Corp., known as SpaceX, is an American aerospace manufacturer and space transport services company headquartered in Hawthorne, California. It was founded in 2002 by entrepreneur Elon Musk with the goal of reducing space transportation costs and enabling the colonization of Mars. SpaceX operates from many pads, on the East Coast of the US they operate from SLC-40 at Cape Canaveral Space Force Station and historic LC-39A at Kennedy Space Center. They also operate from SLC-4E at Vandenberg Space Force Base, California, usually for polar launches. Another launch site is being developed at Boca Chica, Texas.",
                "administrator": "CEO: Elon Musk",
                "founding_year": "2002",
                "launchers": "Falcon | Starship",
                "spacecraft": "Dragon",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/spacex_image_20190207032501.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/spacex_logo_20220826094919.png"
            },
            "in_use": true,
            "capability": "Crew Flights to ISS or Low Earth Orbit",
            "maiden_flight": "2019-03-02",
            "human_rated": true,
            "crew_capacity": 4,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/spacex_dm-2_cre_image_20200504065311.jpeg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Dragon_2",
            "info_link": "https://www.spacex.com/crew-dragon"
        },
        {
            "id": 9,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/9/?format=api",
            "name": "CST-100 Starliner",
            "agency": {
                "id": 80,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/80/?format=api",
                "name": "Boeing",
                "featured": false,
                "type": "Commercial",
                "country_code": "USA",
                "abbrev": "BA",
                "description": "Boeing as a space agency has recently provided NASA with assistance on sending humans to the ISS from American with both their construction of the CST-100 Starliner crew capsule and their work on the SLS Avionics to return to the moon and beyond. Their ventures in GPS satellite systems and Tracking and Data Relay Satellites provide information about earth-orbiting craft to stations on the ground. They also enable research on the ISS and will be helping with the construction of the Lunar Gateway.",
                "administrator": "Leanne Caret",
                "founding_year": "2002",
                "launchers": "SLS",
                "spacecraft": "Starliner",
                "parent": null,
                "image_url": 'https://cdn.mos.cms.futurecdn.net/BoRGKpx3RWAk2qb8W7HTVi-1200-80.jpg',
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/boeing_logo_20201128183345.png"
            },
            "in_use": true,
            "capability": "Cargo and Human Transportation",
            "maiden_flight": "2019-08-17",
            "human_rated": true,
            "crew_capacity": 7,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/boeing_starline_image_20220525180700.jpeg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Boeing_CST-100_Starliner",
            "info_link": "http://www.boeing.com/space/starliner/"
        },
        {
            "id": 19,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/19/?format=api",
            "name": "Cygnus Enhanced",
            "agency": {
                "id": 257,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/257/?format=api",
                "name": "Northrop Grumman Space Systems",
                "featured": true,
                "type": "Commercial",
                "country_code": "USA",
                "abbrev": "NGSS",
                "description": "Northrup Grumman Space Systems designs, builds and delivers space, defence and aviation-related systems to customers around the world. They aquired Orbital ATK in 2018 along with its launchers and ongoing missions.",
                "administrator": "CEO: Kathy Warden",
                "founding_year": "2015",
                "launchers": "Antares | Minotaur | Pegasus",
                "spacecraft": "Cygnus",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/northrop2520grumman2520innovation2520systems_image_20190207032451.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/northrop2520grumman2520innovation2520systems_logo_20190207032451.png"
            },
            "in_use": true,
            "capability": "Cargo Earth Orbit Logistics",
            "maiden_flight": "2015-12-06",
            "human_rated": false,
            "crew_capacity": null,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/cygnus2520enhanced_image_20190207032513.jpeg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Cygnus_(spacecraft)",
            "info_link": ""
        },
        {
            "id": 5,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/5/?format=api",
            "name": "Cygnus Standard",
            "agency": {
                "id": 257,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/257/?format=api",
                "name": "Northrop Grumman Space Systems",
                "featured": true,
                "type": "Commercial",
                "country_code": "USA",
                "abbrev": "NGSS",
                "description": "Northrup Grumman Space Systems designs, builds and delivers space, defence and aviation-related systems to customers around the world. They aquired Orbital ATK in 2018 along with its launchers and ongoing missions.",
                "administrator": "CEO: Kathy Warden",
                "founding_year": "2015",
                "launchers": "Antares | Minotaur | Pegasus",
                "spacecraft": "Cygnus",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/northrop2520grumman2520innovation2520systems_image_20190207032451.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/northrop2520grumman2520innovation2520systems_logo_20190207032451.png"
            },
            "in_use": false,
            "capability": "Cargo Earth Orbit Logistics",
            "maiden_flight": "2013-09-18",
            "human_rated": false,
            "crew_capacity": null,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/cygnus2520standard_image_20190207032514.jpeg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Cygnus_(spacecraft)",
            "info_link": ""
        },
        {
            "id": 32,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/32/?format=api",
            "name": "Cygnus Upgraded",
            "agency": {
                "id": 257,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/257/?format=api",
                "name": "Northrop Grumman Space Systems",
                "featured": true,
                "type": "Commercial",
                "country_code": "USA",
                "abbrev": "NGSS",
                "description": "Northrup Grumman Space Systems designs, builds and delivers space, defence and aviation-related systems to customers around the world. They aquired Orbital ATK in 2018 along with its launchers and ongoing missions.",
                "administrator": "CEO: Kathy Warden",
                "founding_year": "2015",
                "launchers": "Antares | Minotaur | Pegasus",
                "spacecraft": "Cygnus",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/northrop2520grumman2520innovation2520systems_image_20190207032451.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/northrop2520grumman2520innovation2520systems_logo_20190207032451.png"
            },
            "in_use": false,
            "capability": "Cargo Earth Orbit Logistics",
            "maiden_flight": null,
            "human_rated": false,
            "crew_capacity": null,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/cygnus2520enhanced_image_20190207032513.jpeg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Cygnus_(spacecraft)",
            "info_link": ""
        },
        {
            "id": 3,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/3/?format=api",
            "name": "Dragon 1",
            "agency": {
                "id": 121,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/121/?format=api",
                "name": "SpaceX",
                "featured": true,
                "type": "Commercial",
                "country_code": "USA",
                "abbrev": "SpX",
                "description": "Space Exploration Technologies Corp., known as SpaceX, is an American aerospace manufacturer and space transport services company headquartered in Hawthorne, California. It was founded in 2002 by entrepreneur Elon Musk with the goal of reducing space transportation costs and enabling the colonization of Mars. SpaceX operates from many pads, on the East Coast of the US they operate from SLC-40 at Cape Canaveral Space Force Station and historic LC-39A at Kennedy Space Center. They also operate from SLC-4E at Vandenberg Space Force Base, California, usually for polar launches. Another launch site is being developed at Boca Chica, Texas.",
                "administrator": "CEO: Elon Musk",
                "founding_year": "2002",
                "launchers": "Falcon | Starship",
                "spacecraft": "Dragon",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/spacex_image_20190207032501.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/spacex_logo_20220826094919.png"
            },
            "in_use": false,
            "capability": "ISS Logistics",
            "maiden_flight": "2010-12-08",
            "human_rated": false,
            "crew_capacity": null,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/crs-172520dragon2520berthing_image_20190318203226.jpeg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Dragon_(spacecraft)",
            "info_link": "https://www.spacex.com/dragon"
        },
        {
            "id": 24,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/24/?format=api",
            "name": "Dream Chaser",
            "agency": {
                "id": 1020,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/1020/?format=api",
                "name": "Sierra Nevada Corporation",
                "featured": false,
                "type": "Commercial",
                "country_code": "USA",
                "abbrev": "SNC",
                "description": "Sierra Nevada Corporation (SNC) is an American, privately held aerospace and national security contractor specializing in aircraft modification and integration, high performance space components and systems, and commercial solutions. The company contracts with the United States Armed Forces, NASA and private spaceflight companies.",
                "administrator": "CEO: Fatih Ozmen",
                "founding_year": "1963",
                "launchers": "",
                "spacecraft": "",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/sierra_nevada_c_image_20200821083933.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/sierra2520nevada2520corporation_logo_20200821083933.png"
            },
            "in_use": true,
            "capability": "Cargo transportation to and from the ISS.",
            "maiden_flight": null,
            "human_rated": false,
            "crew_capacity": 7,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/dream_chaser_image_20200821084247.jpeg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Dream_Chaser",
            "info_link": "https://www.sncorp.com/what-we-do/dream-chaser-space-vehicle/"
        },
        {
            "id": 29,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/29/?format=api",
            "name": "Gaganyaan",
            "agency": {
                "id": 1031,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/1031/?format=api",
                "name": "Hindustan Aeronautics Limited",
                "featured": false,
                "type": "Government",
                "country_code": "IND",
                "abbrev": "HAL",
                "description": "Hindustan Aeronautics Limited is an Indian state-owned aerospace and defence company, headquartered in Bengaluru, India. Established on 23 December 1940, HAL is one of the oldest and largest aerospace and defence manufacturers in the world.",
                "administrator": "Chairman: R. Madhavan",
                "founding_year": "1940",
                "launchers": "",
                "spacecraft": "Gaganyaan",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/hindustan_aeron_image_20220205093649.png",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/hindustan2520aeronautics2520limited_logo_20220205093649.png"
            },
            "in_use": true,
            "capability": "The spacecraft is being designed to carry three people, and a planned upgraded version will be equipped with rendezvous and docking capability.",
            "maiden_flight": "2023-10-21",
            "human_rated": true,
            "crew_capacity": 3,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/gaganyaan_image_20231021132705.jpeg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Gaganyaan",
            "info_link": "https://www.isro.gov.in/frequently-asked-questions/gaganyaan"
        },
        {
            "id": 12,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/12/?format=api",
            "name": "Gemini",
            "agency": {
                "id": 44,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/44/?format=api",
                "name": "National Aeronautics and Space Administration",
                "featured": true,
                "type": "Government",
                "country_code": "USA",
                "abbrev": "NASA",
                "description": "The National Aeronautics and Space Administration is an independent agency of the executive branch of the United States federal government responsible for the civilian space program, as well as aeronautics and aerospace research. NASA have many launch facilities but most are inactive. The most commonly used pad will be LC-39B at Kennedy Space Center in Florida.",
                "administrator": "Administrator: Bill Nelson",
                "founding_year": "1958",
                "launchers": "Space Shuttle | SLS",
                "spacecraft": "Orion",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/national2520aeronautics2520and2520space2520administration_image_20190207032448.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/national2520aeronautics2520and2520space2520administration_logo_20190207032448.png"
            },
            "in_use": false,
            "capability": "Human transportation to low Earth orbit.",
            "maiden_flight": "1964-04-08",
            "human_rated": true,
            "crew_capacity": 2,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/gemini_image_20190207032517.jpeg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Project_Gemini#Spacecraft",
            "info_link": ""
        },
        {
            "id": 18,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/18/?format=api",
            "name": "H-II Transfer Vehicle (HTV)",
            "agency": {
                "id": 37,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/37/?format=api",
                "name": "Japan Aerospace Exploration Agency",
                "featured": true,
                "type": "Government",
                "country_code": "JPN",
                "abbrev": "JAXA",
                "description": "The Japan Aerospace Exploration Agency (JAXA) is Japan's national aero-space agency. Through the merger of three previously independent organizations, JAXA was formed on 1 October 2003. JAXA is responsible for research, technology development and the launch of satellites into orbit, and is involved in many more advanced missions, such as asteroid exploration and possible manned exploration of the Moon. JAXA launch their Epsilon vehicle from the Uchinoura Space Center and their H-II vehicles from the Tanegashima Space Center.",
                "administrator": "Administrator: Hiroshi Yamakawa",
                "founding_year": "2003",
                "launchers": "H-II",
                "spacecraft": "",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/japan2520aerospace2520exploration2520agency_image_20190207032440.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/japan2520aerospace2520exploration2520agency_logo_20190207032440.png"
            },
            "in_use": false,
            "capability": "Cargo Earth Orbit Logistics",
            "maiden_flight": "2009-09-10",
            "human_rated": false,
            "crew_capacity": null,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/htv-4_captured__image_20240325122159.jpeg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/H-II_Transfer_Vehicle",
            "info_link": ""
        },
        {
            "id": 11,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/11/?format=api",
            "name": "Mercury",
            "agency": {
                "id": 44,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/44/?format=api",
                "name": "National Aeronautics and Space Administration",
                "featured": true,
                "type": "Government",
                "country_code": "USA",
                "abbrev": "NASA",
                "description": "The National Aeronautics and Space Administration is an independent agency of the executive branch of the United States federal government responsible for the civilian space program, as well as aeronautics and aerospace research. NASA have many launch facilities but most are inactive. The most commonly used pad will be LC-39B at Kennedy Space Center in Florida.",
                "administrator": "Administrator: Bill Nelson",
                "founding_year": "1958",
                "launchers": "Space Shuttle | SLS",
                "spacecraft": "Orion",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/national2520aeronautics2520and2520space2520administration_image_20190207032448.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/national2520aeronautics2520and2520space2520administration_logo_20190207032448.png"
            },
            "in_use": false,
            "capability": "Human transportation to upper Earth atmosphere and low Earth orbit.",
            "maiden_flight": "1961-05-05",
            "human_rated": true,
            "crew_capacity": 1,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/mercury_image_20190207032519.jpeg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Project_Mercury#Spacecraft",
            "info_link": ""
        },
        {
            "id": 13,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/13/?format=api",
            "name": "North American X-15",
            "agency": {
                "id": 44,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/44/?format=api",
                "name": "National Aeronautics and Space Administration",
                "featured": true,
                "type": "Government",
                "country_code": "USA",
                "abbrev": "NASA",
                "description": "The National Aeronautics and Space Administration is an independent agency of the executive branch of the United States federal government responsible for the civilian space program, as well as aeronautics and aerospace research. NASA have many launch facilities but most are inactive. The most commonly used pad will be LC-39B at Kennedy Space Center in Florida.",
                "administrator": "Administrator: Bill Nelson",
                "founding_year": "1958",
                "launchers": "Space Shuttle | SLS",
                "spacecraft": "Orion",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/national2520aeronautics2520and2520space2520administration_image_20190207032448.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/national2520aeronautics2520and2520space2520administration_logo_20190207032448.png"
            },
            "in_use": false,
            "capability": "Experimental aircraft used for Aircraft and Spacecraft design",
            "maiden_flight": "1959-06-08",
            "human_rated": true,
            "crew_capacity": 1,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/north2520american2520x-15_image_20190207032520.jpeg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/North_American_X-15",
            "info_link": "https://airandspace.si.edu/collection-objects/north-american-x-15"
        },
        {
            "id": 4,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/4/?format=api",
            "name": "Orion",
            "agency": {
                "id": 44,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/44/?format=api",
                "name": "National Aeronautics and Space Administration",
                "featured": true,
                "type": "Government",
                "country_code": "USA",
                "abbrev": "NASA",
                "description": "The National Aeronautics and Space Administration is an independent agency of the executive branch of the United States federal government responsible for the civilian space program, as well as aeronautics and aerospace research. NASA have many launch facilities but most are inactive. The most commonly used pad will be LC-39B at Kennedy Space Center in Florida.",
                "administrator": "Administrator: Bill Nelson",
                "founding_year": "1958",
                "launchers": "Space Shuttle | SLS",
                "spacecraft": "Orion",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/national2520aeronautics2520and2520space2520administration_image_20190207032448.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/national2520aeronautics2520and2520space2520administration_logo_20190207032448.png"
            },
            "in_use": true,
            "capability": "Lunar Missions.",
            "maiden_flight": "2022-11-16",
            "human_rated": true,
            "crew_capacity": 4,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/orion_image_20231118102035.jpeg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Orion_(spacecraft)",
            "info_link": ""
        },
        {
            "id": 8,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/8/?format=api",
            "name": "Progress 7K-TG",
            "agency": {
                "id": 63,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/63/?format=api",
                "name": "Russian Federal Space Agency (ROSCOSMOS)",
                "featured": true,
                "type": "Government",
                "country_code": "RUS",
                "abbrev": "RFSA",
                "description": "The Roscosmos State Corporation for Space Activities, commonly known as Roscosmos, is the governmental body responsible for the space science program of the Russian Federation and general aerospace research. Soyuz has many launch locations the Russian sites are Baikonur, Plesetsk and Vostochny however Ariane also purchases the vehicle and launches it from French Guiana.",
                "administrator": "Administrator: Yuri Borisov",
                "founding_year": "1992",
                "launchers": "Soyuz",
                "spacecraft": "Soyuz",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/russian2520federal2520space2520agency25202528roscosmos2529_image_20190207032459.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/russian2520federal2520space2520agency25202528roscosmos2529_logo_20190207032459.png"
            },
            "in_use": false,
            "capability": "Salyut-7 & Mir Logistics",
            "maiden_flight": "1978-01-20",
            "human_rated": false,
            "crew_capacity": null,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/progress_7k-tg_image_20231220085840.png",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Progress_(spacecraft)",
            "info_link": "https://www.nasa.gov/mission_pages/station/structure/elements/progress.html"
        },
        {
            "id": 35,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/35/?format=api",
            "name": "Progress-M",
            "agency": {
                "id": 63,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/63/?format=api",
                "name": "Russian Federal Space Agency (ROSCOSMOS)",
                "featured": true,
                "type": "Government",
                "country_code": "RUS",
                "abbrev": "RFSA",
                "description": "The Roscosmos State Corporation for Space Activities, commonly known as Roscosmos, is the governmental body responsible for the space science program of the Russian Federation and general aerospace research. Soyuz has many launch locations the Russian sites are Baikonur, Plesetsk and Vostochny however Ariane also purchases the vehicle and launches it from French Guiana.",
                "administrator": "Administrator: Yuri Borisov",
                "founding_year": "1992",
                "launchers": "Soyuz",
                "spacecraft": "Soyuz",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/russian2520federal2520space2520agency25202528roscosmos2529_image_20190207032459.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/russian2520federal2520space2520agency25202528roscosmos2529_logo_20190207032459.png"
            },
            "in_use": false,
            "capability": "ISS & Mir Logistics, ISS & Mir Orbit Raising",
            "maiden_flight": "1989-08-23",
            "human_rated": false,
            "crew_capacity": null,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/progress-m_image_20231219141001.jpeg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Progress-M",
            "info_link": ""
        },
        {
            "id": 36,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/36/?format=api",
            "name": "Progress-M1",
            "agency": {
                "id": 63,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/63/?format=api",
                "name": "Russian Federal Space Agency (ROSCOSMOS)",
                "featured": true,
                "type": "Government",
                "country_code": "RUS",
                "abbrev": "RFSA",
                "description": "The Roscosmos State Corporation for Space Activities, commonly known as Roscosmos, is the governmental body responsible for the space science program of the Russian Federation and general aerospace research. Soyuz has many launch locations the Russian sites are Baikonur, Plesetsk and Vostochny however Ariane also purchases the vehicle and launches it from French Guiana.",
                "administrator": "Administrator: Yuri Borisov",
                "founding_year": "1992",
                "launchers": "Soyuz",
                "spacecraft": "Soyuz",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/russian2520federal2520space2520agency25202528roscosmos2529_image_20190207032459.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/russian2520federal2520space2520agency25202528roscosmos2529_logo_20190207032459.png"
            },
            "in_use": false,
            "capability": "ISS Propellant Refueling, Mir Deorbiting",
            "maiden_flight": "2000-02-01",
            "human_rated": false,
            "crew_capacity": null,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/progress-m1_image_20231219142545.jpeg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Progress-M1",
            "info_link": ""
        },
        {
            "id": 34,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/34/?format=api",
            "name": "Progress-M (modified)",
            "agency": {
                "id": 63,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/63/?format=api",
                "name": "Russian Federal Space Agency (ROSCOSMOS)",
                "featured": true,
                "type": "Government",
                "country_code": "RUS",
                "abbrev": "RFSA",
                "description": "The Roscosmos State Corporation for Space Activities, commonly known as Roscosmos, is the governmental body responsible for the space science program of the Russian Federation and general aerospace research. Soyuz has many launch locations the Russian sites are Baikonur, Plesetsk and Vostochny however Ariane also purchases the vehicle and launches it from French Guiana.",
                "administrator": "Administrator: Yuri Borisov",
                "founding_year": "1992",
                "launchers": "Soyuz",
                "spacecraft": "Soyuz",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/russian2520federal2520space2520agency25202528roscosmos2529_image_20190207032459.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/russian2520federal2520space2520agency25202528roscosmos2529_logo_20190207032459.png"
            },
            "in_use": false,
            "capability": "ISS Logistics, ISS Orbit Raising",
            "maiden_flight": "2008-11-26",
            "human_rated": false,
            "crew_capacity": null,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/progress-m_252_image_20231219140115.jpeg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Progress-M",
            "info_link": ""
        },
        {
            "id": 33,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/33/?format=api",
            "name": "Progress-MS",
            "agency": {
                "id": 63,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/63/?format=api",
                "name": "Russian Federal Space Agency (ROSCOSMOS)",
                "featured": true,
                "type": "Government",
                "country_code": "RUS",
                "abbrev": "RFSA",
                "description": "The Roscosmos State Corporation for Space Activities, commonly known as Roscosmos, is the governmental body responsible for the space science program of the Russian Federation and general aerospace research. Soyuz has many launch locations the Russian sites are Baikonur, Plesetsk and Vostochny however Ariane also purchases the vehicle and launches it from French Guiana.",
                "administrator": "Administrator: Yuri Borisov",
                "founding_year": "1992",
                "launchers": "Soyuz",
                "spacecraft": "Soyuz",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/russian2520federal2520space2520agency25202528roscosmos2529_image_20190207032459.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/russian2520federal2520space2520agency25202528roscosmos2529_logo_20190207032459.png"
            },
            "in_use": true,
            "capability": "ISS Logistics, ISS Orbit Raising",
            "maiden_flight": "2015-12-21",
            "human_rated": false,
            "crew_capacity": null,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/progress-ms_image_20231219150735.jpeg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Progress_(spacecraft)#Progress_MS_(2015%E2%80%93present)",
            "info_link": ""
        },
        {
            "id": 37,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/37/?format=api",
            "name": "Progress M-UM",
            "agency": {
                "id": 63,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/63/?format=api",
                "name": "Russian Federal Space Agency (ROSCOSMOS)",
                "featured": true,
                "type": "Government",
                "country_code": "RUS",
                "abbrev": "RFSA",
                "description": "The Roscosmos State Corporation for Space Activities, commonly known as Roscosmos, is the governmental body responsible for the space science program of the Russian Federation and general aerospace research. Soyuz has many launch locations the Russian sites are Baikonur, Plesetsk and Vostochny however Ariane also purchases the vehicle and launches it from French Guiana.",
                "administrator": "Administrator: Yuri Borisov",
                "founding_year": "1992",
                "launchers": "Soyuz",
                "spacecraft": "Soyuz",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/russian2520federal2520space2520agency25202528roscosmos2529_image_20190207032459.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/russian2520federal2520space2520agency25202528roscosmos2529_logo_20190207032459.png"
            },
            "in_use": false,
            "capability": "ISS Module Delivery",
            "maiden_flight": "2021-11-24",
            "human_rated": false,
            "crew_capacity": null,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/progress_m-um_image_20231221195834.jpg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Progress_M-UM",
            "info_link": ""
        },
        {
            "id": 2,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/2/?format=api",
            "name": "Shenzhou",
            "agency": {
                "id": 17,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/17/?format=api",
                "name": "China National Space Administration",
                "featured": true,
                "type": "Government",
                "country_code": "CHN",
                "abbrev": "CNSA",
                "description": "The China National Space Administration (CNSA) is the national space agency of the People's Republic of China. It is responsible for the national space program and for planning and development of space activities. CNSA and China Aerospace Corporation (CASC) assumed the authority over space development efforts previously held by the Ministry of Aerospace Industry. The CNSA has many launch sites around China with their orbital sites located in Jiuquan, Xichang, Taiyuan and Wenchang.",
                "administrator": "Administrator: Tang Dengjie",
                "founding_year": "1993",
                "launchers": "",
                "spacecraft": "Shenzhou",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/china2520national2520space2520administration_image_20190207032431.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/china2520national2520space2520administration_logo_20190207032431.png"
            },
            "in_use": true,
            "capability": "Chinese crewed spaceflight program.",
            "maiden_flight": "1999-11-19",
            "human_rated": true,
            "crew_capacity": 3,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/shenzhou_image_20190207032522.jpeg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Shenzhou_(spacecraft)",
            "info_link": ""
        },
        {
            "id": 1,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/1/?format=api",
            "name": "Soyuz",
            "agency": {
                "id": 63,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/63/?format=api",
                "name": "Russian Federal Space Agency (ROSCOSMOS)",
                "featured": true,
                "type": "Government",
                "country_code": "RUS",
                "abbrev": "RFSA",
                "description": "The Roscosmos State Corporation for Space Activities, commonly known as Roscosmos, is the governmental body responsible for the space science program of the Russian Federation and general aerospace research. Soyuz has many launch locations the Russian sites are Baikonur, Plesetsk and Vostochny however Ariane also purchases the vehicle and launches it from French Guiana.",
                "administrator": "Administrator: Yuri Borisov",
                "founding_year": "1992",
                "launchers": "Soyuz",
                "spacecraft": "Soyuz",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/russian2520federal2520space2520agency25202528roscosmos2529_image_20190207032459.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/russian2520federal2520space2520agency25202528roscosmos2529_logo_20190207032459.png"
            },
            "in_use": false,
            "capability": "Manned and Cargo ISS Logistics",
            "maiden_flight": "1966-11-28",
            "human_rated": true,
            "crew_capacity": 3,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/soyuz_image_20201015191152.jpg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Soyuz_(spacecraft)",
            "info_link": ""
        },
        {
            "id": 38,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/38/?format=api",
            "name": "Soyuz MS",
            "agency": {
                "id": 63,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/63/?format=api",
                "name": "Russian Federal Space Agency (ROSCOSMOS)",
                "featured": true,
                "type": "Government",
                "country_code": "RUS",
                "abbrev": "RFSA",
                "description": "The Roscosmos State Corporation for Space Activities, commonly known as Roscosmos, is the governmental body responsible for the space science program of the Russian Federation and general aerospace research. Soyuz has many launch locations the Russian sites are Baikonur, Plesetsk and Vostochny however Ariane also purchases the vehicle and launches it from French Guiana.",
                "administrator": "Administrator: Yuri Borisov",
                "founding_year": "1992",
                "launchers": "Soyuz",
                "spacecraft": "Soyuz",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/russian2520federal2520space2520agency25202528roscosmos2529_image_20190207032459.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/russian2520federal2520space2520agency25202528roscosmos2529_logo_20190207032459.png"
            },
            "in_use": true,
            "capability": "Manned and Cargo ISS Logistics, Lifeboat",
            "maiden_flight": "2016-07-07",
            "human_rated": true,
            "crew_capacity": 3,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/soyuz_ms_in_orb_image_20240313130407.jpeg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Soyuz_MS",
            "info_link": ""
        },
        {
            "id": 42,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/42/?format=api",
            "name": "Soyuz T",
            "agency": {
                "id": 63,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/63/?format=api",
                "name": "Russian Federal Space Agency (ROSCOSMOS)",
                "featured": true,
                "type": "Government",
                "country_code": "RUS",
                "abbrev": "RFSA",
                "description": "The Roscosmos State Corporation for Space Activities, commonly known as Roscosmos, is the governmental body responsible for the space science program of the Russian Federation and general aerospace research. Soyuz has many launch locations the Russian sites are Baikonur, Plesetsk and Vostochny however Ariane also purchases the vehicle and launches it from French Guiana.",
                "administrator": "Administrator: Yuri Borisov",
                "founding_year": "1992",
                "launchers": "Soyuz",
                "spacecraft": "Soyuz",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/russian2520federal2520space2520agency25202528roscosmos2529_image_20190207032459.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/russian2520federal2520space2520agency25202528roscosmos2529_logo_20190207032459.png"
            },
            "in_use": false,
            "capability": "Manned and Cargo Salyut & Mir Logistics, Lifeboat",
            "maiden_flight": "1979-12-16",
            "human_rated": true,
            "crew_capacity": 3,
            "image_url": "https://hips.hearstapps.com/pop.h-cdn.co/assets/16/48/1480349224-soyuz-7k-ok-in-orbit.jpg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Soyuz-T",
            "info_link": ""
        },
        {
            "id": 41,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/41/?format=api",
            "name": "Soyuz TM",
            "agency": {
                "id": 63,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/63/?format=api",
                "name": "Russian Federal Space Agency (ROSCOSMOS)",
                "featured": true,
                "type": "Government",
                "country_code": "RUS",
                "abbrev": "RFSA",
                "description": "The Roscosmos State Corporation for Space Activities, commonly known as Roscosmos, is the governmental body responsible for the space science program of the Russian Federation and general aerospace research. Soyuz has many launch locations the Russian sites are Baikonur, Plesetsk and Vostochny however Ariane also purchases the vehicle and launches it from French Guiana.",
                "administrator": "Administrator: Yuri Borisov",
                "founding_year": "1992",
                "launchers": "Soyuz",
                "spacecraft": "Soyuz",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/russian2520federal2520space2520agency25202528roscosmos2529_image_20190207032459.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/russian2520federal2520space2520agency25202528roscosmos2529_logo_20190207032459.png"
            },
            "in_use": false,
            "capability": "Manned and Cargo ISS & Mir Logistics, Lifeboat",
            "maiden_flight": "1986-05-21",
            "human_rated": true,
            "crew_capacity": 3,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/soyuz_tm_image_20231228130713.jpeg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Soyuz-TM",
            "info_link": ""
        },
        {
            "id": 40,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/40/?format=api",
            "name": "Soyuz TMA",
            "agency": {
                "id": 63,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/63/?format=api",
                "name": "Russian Federal Space Agency (ROSCOSMOS)",
                "featured": true,
                "type": "Government",
                "country_code": "RUS",
                "abbrev": "RFSA",
                "description": "The Roscosmos State Corporation for Space Activities, commonly known as Roscosmos, is the governmental body responsible for the space science program of the Russian Federation and general aerospace research. Soyuz has many launch locations the Russian sites are Baikonur, Plesetsk and Vostochny however Ariane also purchases the vehicle and launches it from French Guiana.",
                "administrator": "Administrator: Yuri Borisov",
                "founding_year": "1992",
                "launchers": "Soyuz",
                "spacecraft": "Soyuz",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/russian2520federal2520space2520agency25202528roscosmos2529_image_20190207032459.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/russian2520federal2520space2520agency25202528roscosmos2529_logo_20190207032459.png"
            },
            "in_use": false,
            "capability": "Manned and Cargo ISS Logistics, Lifeboat",
            "maiden_flight": "2002-10-30",
            "human_rated": true,
            "crew_capacity": 3,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/soyuz_tma_image_20231225093222.jpeg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Soyuz_TMA",
            "info_link": ""
        },
        {
            "id": 39,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/39/?format=api",
            "name": "Soyuz TMA-M",
            "agency": {
                "id": 63,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/63/?format=api",
                "name": "Russian Federal Space Agency (ROSCOSMOS)",
                "featured": true,
                "type": "Government",
                "country_code": "RUS",
                "abbrev": "RFSA",
                "description": "The Roscosmos State Corporation for Space Activities, commonly known as Roscosmos, is the governmental body responsible for the space science program of the Russian Federation and general aerospace research. Soyuz has many launch locations the Russian sites are Baikonur, Plesetsk and Vostochny however Ariane also purchases the vehicle and launches it from French Guiana.",
                "administrator": "Administrator: Yuri Borisov",
                "founding_year": "1992",
                "launchers": "Soyuz",
                "spacecraft": "Soyuz",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/russian2520federal2520space2520agency25202528roscosmos2529_image_20190207032459.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/russian2520federal2520space2520agency25202528roscosmos2529_logo_20190207032459.png"
            },
            "in_use": false,
            "capability": "Manned and Cargo ISS Logistics, Lifeboat",
            "maiden_flight": "2010-10-07",
            "human_rated": true,
            "crew_capacity": 3,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/soyuz_tma-m_image_20231225092103.jpeg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Soyuz_TMA#Soyuz_TMA-M",
            "info_link": ""
        },
        {
            "id": 27,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/27/?format=api",
            "name": "SpaceShipTwo",
            "agency": {
                "id": 1024,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/1024/?format=api",
                "name": "Virgin Galactic",
                "featured": false,
                "type": "Private",
                "country_code": "USA",
                "abbrev": "VG",
                "description": "Virgin Galactic is an American spaceflight company within the Virgin Group. It is developing commercial spacecraft and aims to provide suborbital spaceflights to space tourists. Virgin Galactic's suborbital spacecraft are air launched from beneath a carrier airplane known as White Knight Two.",
                "administrator": "Founder: Richard Branson",
                "founding_year": "2004",
                "launchers": "VMS Eve",
                "spacecraft": "VSS Enterprise | VSS Unity",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/virgin_galactic_image_20210522131723.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/virgin2520galactic_logo_20230509082346.png"
            },
            "in_use": true,
            "capability": "SpaceShipTwo is carried to its launch altitude by a Scaled Composites White Knight Two, before being released to fly on into the upper atmosphere powered by its rocket engine. It then glides back to Earth and performs a conventional runway landing.",
            "maiden_flight": "2010-10-10",
            "human_rated": true,
            "crew_capacity": 8,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/spaceshiptwo_image_20210522133744.jpeg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/SpaceShipTwo",
            "info_link": "https://www.virgingalactic.com/"
        },
        {
            "id": 14,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/14/?format=api",
            "name": "Space Shuttle",
            "agency": {
                "id": 44,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/44/?format=api",
                "name": "National Aeronautics and Space Administration",
                "featured": true,
                "type": "Government",
                "country_code": "USA",
                "abbrev": "NASA",
                "description": "The National Aeronautics and Space Administration is an independent agency of the executive branch of the United States federal government responsible for the civilian space program, as well as aeronautics and aerospace research. NASA have many launch facilities but most are inactive. The most commonly used pad will be LC-39B at Kennedy Space Center in Florida.",
                "administrator": "Administrator: Bill Nelson",
                "founding_year": "1958",
                "launchers": "Space Shuttle | SLS",
                "spacecraft": "Orion",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/national2520aeronautics2520and2520space2520administration_image_20190207032448.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/national2520aeronautics2520and2520space2520administration_logo_20190207032448.png"
            },
            "in_use": false,
            "capability": "Carrying a crew of 7 astronauts along with cargo to Low Earth Orbit.",
            "maiden_flight": "1981-04-12",
            "human_rated": true,
            "crew_capacity": 7,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/space2520shuttle_image_20190207032524.jpeg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Space_Shuttle",
            "info_link": ""
        },
        {
            "id": 26,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/26/?format=api",
            "name": "Starship",
            "agency": {
                "id": 121,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/121/?format=api",
                "name": "SpaceX",
                "featured": true,
                "type": "Commercial",
                "country_code": "USA",
                "abbrev": "SpX",
                "description": "Space Exploration Technologies Corp., known as SpaceX, is an American aerospace manufacturer and space transport services company headquartered in Hawthorne, California. It was founded in 2002 by entrepreneur Elon Musk with the goal of reducing space transportation costs and enabling the colonization of Mars. SpaceX operates from many pads, on the East Coast of the US they operate from SLC-40 at Cape Canaveral Space Force Station and historic LC-39A at Kennedy Space Center. They also operate from SLC-4E at Vandenberg Space Force Base, California, usually for polar launches. Another launch site is being developed at Boca Chica, Texas.",
                "administrator": "CEO: Elon Musk",
                "founding_year": "2002",
                "launchers": "Falcon | Starship",
                "spacecraft": "Dragon",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/spacex_image_20190207032501.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/spacex_logo_20220826094919.png"
            },
            "in_use": true,
            "capability": "More than 100 tons to Earth orbit",
            "maiden_flight": "2023-04-20",
            "human_rated": false,
            "crew_capacity": 0,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/starship_image_20231116184708.jpeg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/SpaceX_Starship",
            "info_link": "https://www.spacex.com/vehicles/starship/"
        },
        {
            "id": 20,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/20/?format=api",
            "name": "Tesla Roadster",
            "agency": {
                "id": 121,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/121/?format=api",
                "name": "SpaceX",
                "featured": true,
                "type": "Commercial",
                "country_code": "USA",
                "abbrev": "SpX",
                "description": "Space Exploration Technologies Corp., known as SpaceX, is an American aerospace manufacturer and space transport services company headquartered in Hawthorne, California. It was founded in 2002 by entrepreneur Elon Musk with the goal of reducing space transportation costs and enabling the colonization of Mars. SpaceX operates from many pads, on the East Coast of the US they operate from SLC-40 at Cape Canaveral Space Force Station and historic LC-39A at Kennedy Space Center. They also operate from SLC-4E at Vandenberg Space Force Base, California, usually for polar launches. Another launch site is being developed at Boca Chica, Texas.",
                "administrator": "CEO: Elon Musk",
                "founding_year": "2002",
                "launchers": "Falcon | Starship",
                "spacecraft": "Dragon",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/spacex_image_20190207032501.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/spacex_logo_20220826094919.png"
            },
            "in_use": false,
            "capability": "A car in space.",
            "maiden_flight": "2018-02-06",
            "human_rated": false,
            "crew_capacity": 2,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/tesla2520roadster_image_20190307220553.jpg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Elon_Musk%27s_Tesla_Roadster",
            "info_link": ""
        },
        {
            "id": 25,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/25/?format=api",
            "name": "Tianzhou",
            "agency": {
                "id": 88,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/88/?format=api",
                "name": "China Aerospace Science and Technology Corporation",
                "featured": true,
                "type": "Government",
                "country_code": "CHN",
                "abbrev": "CASC",
                "description": "The China Aerospace Science and Technology Corporation (CASC) is the main contractor for the Chinese space program. It is state-owned and has a number of subordinate entities which design, develop and manufacture a range of spacecraft, launch vehicles, strategic and tactical missile systems, and ground equipment. It was officially established in July 1999 as part of a Chinese government reform drive, having previously been one part of the former China Aerospace Corporation. Various incarnations of the program date back to 1956.",
                "administrator": "Chairman & President: Lei Fanpei",
                "founding_year": "1999",
                "launchers": "Long March",
                "spacecraft": "",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/china2520aerospace2520science2520and2520technology2520corporation_image_20191228094408.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/china2520aerospace2520science2520and2520technology2520corporation_logo_20220826093937.png"
            },
            "in_use": true,
            "capability": "Cargo Earth Orbit Logistics",
            "maiden_flight": "2017-04-20",
            "human_rated": false,
            "crew_capacity": null,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/tianzhou_image_20210513100807.jpg",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Tianzhou_(spacecraft)",
            "info_link": ""
        },
        {
            "id": 16,
            "url": "https://ll.thespacedevs.com/2.2.0/config/spacecraft/16/?format=api",
            "name": "Voskhod",
            "agency": {
                "id": 63,
                "url": "https://ll.thespacedevs.com/2.2.0/agencies/63/?format=api",
                "name": "Russian Federal Space Agency (ROSCOSMOS)",
                "featured": true,
                "type": "Government",
                "country_code": "RUS",
                "abbrev": "RFSA",
                "description": "The Roscosmos State Corporation for Space Activities, commonly known as Roscosmos, is the governmental body responsible for the space science program of the Russian Federation and general aerospace research. Soyuz has many launch locations the Russian sites are Baikonur, Plesetsk and Vostochny however Ariane also purchases the vehicle and launches it from French Guiana.",
                "administrator": "Administrator: Yuri Borisov",
                "founding_year": "1992",
                "launchers": "Soyuz",
                "spacecraft": "Soyuz",
                "parent": null,
                "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/russian2520federal2520space2520agency25202528roscosmos2529_image_20190207032459.jpeg",
                "logo_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/russian2520federal2520space2520agency25202528roscosmos2529_logo_20190207032459.png"
            },
            "in_use": false,
            "capability": "Human Spaceflight",
            "maiden_flight": "1964-10-06",
            "human_rated": true,
            "crew_capacity": 3,
            "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/images/voskhod_image_20190207032525.png",
            "nation_url": null,
            "wiki_link": "https://en.wikipedia.org/wiki/Voskhod_(spacecraft)",
            "info_link": ""
        }
    ]
};

// Populate the filter menus
const companies = [...new Set(data.results.map(card => card.agency.name))];
const countryCodes = [...new Set(data.results.map(card => card.agency.country_code))];
const types = [...new Set(data.results.map(card => card.agency.type))];

const companyFilter = document.getElementById('companyFilter');
companies.forEach(company => {
    const option = document.createElement('option');
    option.value = company;
    option.textContent = company;
    companyFilter.appendChild(option);
});

const countryFilter = document.getElementById('countryFilter');
countryCodes.forEach(code => {
    const option = document.createElement('option');
    option.value = code;
    option.textContent = code;
    countryFilter.appendChild(option);
});

const typeFilter = document.getElementById('typeFilter');
types.forEach(type => {
    const option = document.createElement('option');
    option.value = type;
    option.textContent = type;
    typeFilter.appendChild(option);
});


// Display the cards
function renderCards(spacecrafts) {
    const cardsContainer = document.getElementById('cards-container');
    cardsContainer.innerHTML = '';

    spacecrafts.forEach(spacecraft => {
        const card = document.createElement('div');
        card.classList.add('card', 'btn', 'btn-background-slide');
        card.innerHTML = `
            <div class="upper-part">
                <h3>${spacecraft.name}</h3>
                <p>${spacecraft.maiden_flight}</p>
                <p>${spacecraft.capability}</p>
            </div>
            <div class="lower-part">
                <div class="tags">
                    <div class="tag">${spacecraft.agency.country_code}</div>
                    <div class="tag">${spacecraft.agency.abbrev}</div>
                    <div class="tag">${spacecraft.agency.type}</div>
                </div>
            </div>
            <div class="card-image" style="background-image: url(${spacecraft.image_url});"></div>
        `;

        card.addEventListener('click', () => {
            localStorage.setItem('selectedSatellite', JSON.stringify(spacecraft));
            window.location.href = 'sat_detail.html';
        });

        cardsContainer.appendChild(card);
    });
}

// Function to filter cards
function filterCards() {
    const selectedCompany = companyFilter.value;
    const selectedCountry = countryFilter.value;
    const selectedType = typeFilter.value;

    const filteredData = data.results.filter(spacecraft => {
        return (selectedCompany === 'all' || spacecraft.agency.name === selectedCompany) &&
            (selectedCountry === 'all' || spacecraft.agency.country_code === selectedCountry) &&
            (selectedType === 'all' || spacecraft.agency.type === selectedType);
    });

    renderCards(filteredData);
}

// Attach event listeners to the filter menus
companyFilter.addEventListener('change', filterCards);
countryFilter.addEventListener('change', filterCards);
typeFilter.addEventListener('change', filterCards);

// Initial render of all cards
renderCards(data.results);